AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL instance in private subnets with secure SG rules.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

  PrivateSubnet1Id:
    Type: AWS::EC2::Subnet::Id

  PrivateSubnet2Id:
    Type: AWS::EC2::Subnet::Id

  AppSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group of the application/EC2 that will access RDS

  DBUsername:
    Type: String
    Default: admin
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z0-9_]+"

  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    Description: RDS master password

  DBName:
    Type: String
    Default: appdb
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "[a-zA-Z0-9_]+"

Resources:

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL only from app SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref AppSecurityGroupId
      Tags:
        - Key: Name
          Value: RDS-MySQL-SG

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnets for RDS
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: RDS-SubnetGroup

  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      PubliclyAccessible: false
      MultiAZ: false
      BackupRetentionPeriod: 1
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: MySQL-Private-RDS

Outputs:
  RDSEndpoint:
    Description: RDS MySQL endpoint
    Value: !GetAtt MyDB.Endpoint.Address

  RDSPort:
    Description: RDS MySQL port
    Value: !GetAtt MyDB.Endpoint.Port
